export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  SACCO_ADMIN: 'sacco_admin',
  LOAN_OFFICER: 'loan_officer',
  TELLER: 'teller',
  ACCOUNTANT: 'accountant',
  AUDITOR: 'auditor',
  MEMBER: 'member',
  SME_OWNER: 'sme_owner',
  SME_STAFF: 'sme_staff',
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

export const PERMISSIONS = {
  ORGANIZATIONS_VIEW: 'organizations.view',
  ORGANIZATIONS_CREATE: 'organizations.create',
  USERS_MANAGE: 'users.manage',
  MEMBERS_VIEW: 'members.view',
  MEMBERS_MANAGE: 'members.manage',
  LOANS_VIEW: 'loans.view',
  LOANS_APPROVE: 'loans.approve',
  SAVINGS_VIEW: 'savings.view',
  SAVINGS_MANAGE: 'savings.manage',
  ACCOUNTING_VIEW: 'accounting.view',
  ACCOUNTING_MANAGE: 'accounting.manage',
  REPORTS_VIEW: 'reports.view',
  ANALYTICS_VIEW: 'analytics.view',
  PAYMENTS_PROCESS: 'payments.process',
  SME_MANAGE: 'sme.manage',
  INVENTORY_MANAGE: 'inventory.manage',
  AUDIT_VIEW: 'audit.view',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.SACCO_ADMIN]: [
    PERMISSIONS.MEMBERS_VIEW, PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.LOANS_VIEW, PERMISSIONS.LOANS_APPROVE,
    PERMISSIONS.SAVINGS_VIEW, PERMISSIONS.SAVINGS_MANAGE,
    PERMISSIONS.ACCOUNTING_VIEW, PERMISSIONS.ACCOUNTING_MANAGE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.PAYMENTS_PROCESS,
    PERMISSIONS.SME_MANAGE, PERMISSIONS.AUDIT_VIEW,
  ],
  [ROLES.LOAN_OFFICER]: [
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.LOANS_VIEW, PERMISSIONS.LOANS_APPROVE,
    PERMISSIONS.ANALYTICS_VIEW, PERMISSIONS.REPORTS_VIEW,
  ],
  [ROLES.TELLER]: [
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.SAVINGS_MANAGE,
    PERMISSIONS.PAYMENTS_PROCESS,
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.ACCOUNTING_VIEW, PERMISSIONS.ACCOUNTING_MANAGE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.PAYMENTS_PROCESS,
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.MEMBERS_VIEW, PERMISSIONS.LOANS_VIEW,
    PERMISSIONS.SAVINGS_VIEW, PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.AUDIT_VIEW,
  ],
  [ROLES.MEMBER]: [
    PERMISSIONS.SAVINGS_VIEW, PERMISSIONS.LOANS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [ROLES.SME_OWNER]: [
    PERMISSIONS.SME_MANAGE, PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.ANALYTICS_VIEW,
  ],
  [ROLES.SME_STAFF]: [
    PERMISSIONS.SME_MANAGE, PERMISSIONS.INVENTORY_MANAGE,
  ],
};
